setxkbmap -layout us -variant altgr-intl -option nodeadkeys
setxkbmap -option caps:escape
xset r rate 200 30
xinput disable "Synaptics TM3276-022"
xinput set-prop "TPPS/2 IBM TrackPoint" 'libinput Accel Speed' 0.3
exec i3
