# If you come from bash you might have to change your $PATH.
export PATH="/usr/lib/ccache/bin:$HOME/.local/bin:$PATH"
# Add cabal packages to path
export PATH="$HOME/.cabal/bin:$PATH"

export MOZ_ENABLE_WAYLAND=1

# Path to your oh-my-zsh installation.
export ZSH=/home/schmidma/.oh-my-zsh

export JAVA_HOME=/usr/lib/jvm/default/

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="ys"

DEFAULT_USER="schmidma"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
git
ssh-agent
python
pip
sudo
fancy-ctrl-z
wd
extract
zsh-hulks
delete-merged
alias-finder
pass
)

source $ZSH/oh-my-zsh.sh

zstyle ':completion:*' rehash true

# Fish-like syntax highlighting
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_STYLES[path]=none
ZSH_HIGHLIGHT_STYLES[path_prefix]=none

#Fish-like autosuggestions for zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
bindkey '^j' autosuggest-accept

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"
export EDITOR="nvim"
export FZF_DEFAULT_COMMAND="rg --files --no-messages --hidden --follow --ignore-file ~/.ignore"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export LC_CTYPE=en_US.UTF-8

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#
alias startx="exec startx"

alias simrobot=/home/schmidma/worktree/hulks/nao/tools/SimRobot/build/SimRobot\ /home/schmidma/worktree/hulks/nao/tools/SimRobot/Scenes/Penalized.ros2
alias simrobotfull=/home/schmidma/worktree/hulks/nao/tools/SimRobot/build/SimRobot\ /home/schmidma/worktree/hulks/nao/tools/SimRobot/Scenes/TeamHULKs.ros2
alias sim=simrobot
alias simfull=simrobotfull
alias compile=/home/schmidma/worktree/hulks/nao/scripts/compile
alias mate="/home/schmidma/.venv/nao/bin/python3 /home/schmidma/worktree/hulks/nao/tools/mate/run.py"
# alias g=git
alias vedit=nvim\ ~/.config/nvim/init.vim
alias zedit=nvim\ ~/.zshrc
alias duhs="du -hs {.,}* | sort -h"
alias bc="bc -l -q"
alias pdf=evince
alias tt="clear && task"
alias t="task"
alias ta="task add"
alias tat="task add due:today"
alias mutt="cd ~/Downloads && mutt && cd -"
alias rechenknecht="TERM=xterm ssh -X schmidma@10.2.24.6"
alias rules="pdf ~/Documents/HULKs/Rules2019.pdf"

# git merge squash
function gms {
    trackingBranch=$1
    git merge --squash $trackingBranch || { echo 'merge-squashing failed' ; return 1; }
    git commit -m "squashed $trackingBranch"
}


source /usr/share/fzf/key-bindings.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
