# If you come from bash you might have to change your $PATH.
export PATH="$HOME/.cargo/bin:/usr/lib/ccache/bin:$HOME/.local/bin:$PATH"

# use wayland natively if possible
export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=sway
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export CLUTTER_BACKEND=wayland
export SDL_VIDEODRIVER=wayland

# path to oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# GPG SSH support
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpg-connect-agent UPDATESTARTUPTTY /bye &> /dev/null

# enable pass extensions
export PASSWORD_STORE_ENABLE_EXTENSIONS=true

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="ys"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    git
    gh
    python
    pip
    sudo
    fancy-ctrl-z
    wd
    extract
    alias-finder
    pass
)

source $ZSH/oh-my-zsh.sh

# rehash completion database constantly when completing (to find newly installed packages)
zstyle ':completion:*' rehash true

# Fish-like syntax highlighting
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Disable underlining of paths
ZSH_HIGHLIGHT_STYLES[path]=none
ZSH_HIGHLIGHT_STYLES[path_prefix]=none

# Fish-like autosuggestions for zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
bindkey '^j' autosuggest-accept

export EDITOR="nvim"
export FZF_DEFAULT_COMMAND="rg --files --no-messages --hidden --follow --ignore-file ~/.ignore"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export LC_CTYPE=en_US.UTF-8

# aliases
alias vedit=nvim\ ~/.config/nvim/init.vim
alias zedit=nvim\ ~/.dotfiles/dotfiles/zshrc
alias duhs="du -hs {.,}* | sort -h"
alias bc="bc -l -q"
alias pdf=evince
alias tt="clear && task"
alias t="task"
alias ta="task add"
alias tat="task add due:today"

alias simrobot="QT_QPA_PLATFORM= XDG_SESSION_TYPE=tty /home/schmidma/worktree/hulks/nao/tools/SimRobot/build/SimRobot /home/schmidma/worktree/hulks/nao/tools/SimRobot/Scenes/Penalized.ros2"
alias simrobotfull="QT_QPA_PLATFORM= XDG_SESSION_TYPE=tty /home/schmidma/worktree/hulks/nao/tools/SimRobot/build/SimRobot /home/schmidma/worktree/hulks/nao/tools/SimRobot/Scenes/TeamHULKs.ros2"
alias sim=simrobot
alias simfull=simrobotfull
alias compile=/home/schmidma/worktree/hulks/nao/scripts/compile
alias mate="/home/schmidma/.venv/nao/bin/python3 /home/schmidma/worktree/hulks/nao/tools/mate/run.py"
alias rechenknecht="TERM=alacritty ssh schmidma@rechenknecht.hulks.dev"
alias rules="pdf ~/Documents/HULKs/SPL-Rules_2020.pdf"
alias neomutt="cd ~/Downloads && neomutt && cd -"

# git merge squash
function gms {
    trackingBranch=$1
    git merge --squash $trackingBranch || { echo 'merge-squashing failed' ; return 1; }
    git commit -m "squashed $trackingBranch"
}

# You should use - suggesting abbreviations instead of typed command
source /usr/share/zsh/plugins/zsh-you-should-use/you-should-use.plugin.zsh

# source fzf completions
source /usr/share/fzf/completion.zsh
source /usr/share/fzf/key-bindings.zsh
