config:
  backup: true
  create: true
  dotpath: dotfiles
  longkey: true
dotfiles:
  f_zshrc:
    link: link
    src: zshrc
    dst: ~/.zshrc
  f_nvidia-xinitrc:
    link: link
    src: nvidia-xinitrc
    dst: ~/.nvidia-xinitrc
  f_taskrc:
    link: link
    src: taskrc
    dst: ~/.taskrc
  f_Xdefaults:
    link: link
    src: Xdefaults
    dst: ~/.Xdefaults
  f_Xmodmap:
    link: link
    src: Xmodmap
    dst: ~/.Xmodmap
  f_xinitrc:
    link: link
    src: xinitrc
    dst: ~/.xinitrc
  d_config_sway:
    link: link_children
    src: config/sway
    dst: ~/.config/sway
  d_config_swaylock:
    link: link_children
    src: config/swaylock
    dst: ~/.config/swaylock
  d_config_waybar:
    link: link_children
    src: config/waybar
    dst: ~/.config/waybar
  d_config_wofi:
    link: link_children
    src: config/wofi
    dst: ~/.config/wofi
  d_config_termite:
    link: link_children
    src: config/termite
    dst: ~/.config/termite
  d_config_nvim:
    link: link_children
    src: config/nvim
    dst: ~/.config/nvim
    cmpignore:
    - plugged
  d_config_redshift:
    link: link_children
    src: config/redshift
    dst: ~/.config/redshift
  d_config_i3:
    link: link_children
    src: config/i3
    dst: ~/.config/i3
  d_config_rofi:
    link: link_children
    src: config/rofi
    dst: ~/.config/rofi
  d_config_alacritty:
    link: link_children
    src: config/alacritty
    dst: ~/.config/alacritty
  f_gitconfig:
    link: link
    src: gitconfig
    dst: ~/.gitconfig
  d_git-templates:
    link: link_children
    src: git-templates
    dst: ~/.git-templates
  d_config_systemd_user_vdirsyncer.service.d:
    link: link_children
    src: config/systemd/user/vdirsyncer.service.d
    dst: ~/.config/systemd/user/vdirsyncer.service.d
  f_config_environment.d_pass.conf:
    link: link
    src: config/environment.d/pass.conf
    dst: ~/.config/environment.d/pass.conf
  f_config_environment.d_sway.conf:
    link: link
    src: config/environment.d/sway.conf
    dst: ~/.config/environment.d/sway.conf
profiles:
  schmidma-arch:
    dotfiles:
    - f_zshrc
    - f_xinitrc
    - f_nvidia-xinitrc
    - f_taskrc
    - d_config_sway
    - d_config_swaylock
    - d_config_waybar
    - d_config_wofi
    - d_config_termite
    - d_config_nvim
    - d_config_redshift
    - d_config_i3
    - d_config_rofi
    - d_config_alacritty
    - f_gitconfig
    - d_git-templates
    - d_config_systemd_user_vdirsyncer.service.d
    - f_config_environment.d_pass.conf
    - f_config_environment.d_sway.conf
  ubuntu:
    dotfiles:
    - f_zshrc
    - f_xinitrc
    - f_Xmodmap
    - f_Xdefaults
    - d_config_nvim
    - d_config_i3
    - d_config_rofi
    - d_config_redshift
    - d_config_alacritty
