#!/bin/bash

RED="\033[0;31m"
CYAN="\033[0;36m"
MUTED="$(pulsemixer --get-mute --id source-0)"
if [ "$MUTED" -eq "0" ]; then
    echo "";
    echo "";
    echo "#00FFFF"
else
    echo "";
    echo "";
    echo "#FF0000"
fi
