#!/bin/bash

RED="\033[0;31m"
CYAN="\033[0;36m"
MUTED="$(pactl get-source-mute $(pactl get-default-source))"
if [ "$MUTED" = "Mute: no" ]; then
    echo "";
    echo "";
    echo "#00FFFF"
else
    echo "";
    echo "";
    echo "#FF0000"
fi
