theme = "base16_default_dark"

[editor]
line-number = "relative"
color-modes = true
scrolloff = 15
bufferline = "always"
true-color = true
idle-timeout = 0
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace]
render = {"space" = "none", "tab" = "all", "newline" = "none"}

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
"space" = { e = "file_picker", f = ":format" }
g = { j = "goto_previous_buffer", k = "goto_next_buffer"}
G = "goto_file_end"
X = "extend_line_above"
L = ["extend_to_line_bounds", "delete_selection_noyank", "open_above"]
M = ["move_prev_word_start", "move_next_word_end", "search_selection"]

[keys.insert]
"C-space" = "completion"
