[[language]]
name = "rust"
# match-closest-root = true
language-server = { command = "rustup", args = ["run", "nightly", "rust-analyzer"]}

[language.config]
checkOnSave = { command = "clippy" }

[[language]]
name = "latex"

[language.config.texlab]
auxDirectory = "output"

[language.config.texlab.build]
onSave = false
forwardSearchAfter = false

[language.config.texlab.forwardSearch]
executable = "zathura"
args = [ "--synctex-forward", "%l:1:%f", "%p" ]

[language.config.texlab.chktex]
onEdit = true
onOpenAndSave = true