location:
    source_directories:
        - /home/maximilian/
        - /mnt/Terabyte/Documents/
        - /mnt/Terabyte/Music/
        - /mnt/Terabyte/Pictures/
        - /mnt/Terabyte/Videos/

    one_file_system: true

    repositories:
        - u303381@u303381.your-storagebox.de:backups/maximilian-linux

    exclude_patterns:
        - '**/.cache/*'
        - '**/cache/*'
        - '**/Cache/*'
        - '**/CacheStorage/*'
        - '**/Code Cache/*'
        - '~/.local/share/*'
        - '~/.rustup/'
        - '~/.julia/'
        - '~/.mozilla/'
        - '~/.config/discord/*'
        - '~/.npm/'
        - '~/.cargo/'
        - '**/.\#lk*'
        - '*.pyc'
        - '*/.vim*.tmp'

storage:
    encryption_passcommand: bash -c "pass Private/Borg | head -n 1"
    ssh_command: ssh -p 23

consistency:
  checks:
    - disabled

retention:
    keep_daily: 7
    keep_weekly: 4
    keep_monthly: 6
    keep_yearly: 1

hooks:
    before_backup:
        - notify-send "Creating borg backup..."
    after_backup:
        - notify-send "Finished a backup."
    on_error:
        - notify-send -u critical "Error during Borg backup!"
    healthchecks: https://hc-ping.com/c4819100-188d-4671-b20c-6520fd6335f2
